django_working/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include('polls.urls'))
]

polls/urls.py
from django.urls import path
from . import views

app_name = "polls"

urlpatterns = [
  path("", views.index, name='index'),
  path("questions", views.questions, name='questions'),
  path("questions/<int:questionID>", views.questionSingle, name='single_question'),
  path("questions/create", views.formQuestionCreateTemplate, name='create_question'),
  path('questions/create_post', views.formQuestionCreate, name='create_question_post')
]

polls/models.py
from django.db import models


class Question(models.Model):

  def __str__(self):
    return self.question_text

  question_text = models.CharField(max_length=200)
  question_date = models.DateTimeField("Date Published")
  



class Choice(models.Model):


  def __str__(self):
    return self.choice_text

  question_id = models.ForeignKey(Question, on_delete=models.CASCADE)
  choice_text = models.CharField(max_length=200)
  choice_date = models.DateTimeField("Choice published")

polls/views.py
from django.shortcuts import render, reverse
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic

from .models import Question

def index (request):
  return HttpResponse("Hello, i am here.")

def questions(request):
  allQ = Question.objects.all()
  context = {
    "questions" : allQ
  }

  return render(request, "questions.html", context=context )

def questionSingle(request, questionID):
  single = Question.objects.get(pk=questionID)
  context = {
    "question": single
  }
  return render(request, "single-question.html", context=context)

def formQuestionCreateTemplate(request):
  return render(request, 'create-question.html')

def formQuestionCreate(request):
  question_text = request.POST["question_text"]
  question_date = timezone.now()
  newQuestion = Question(question_text=question_text, question_date=question_date)

  newQuestion.save()

  return HttpResponseRedirect(reverse("polls:questions"))

  
  

polls/templates/create-question.html
<h1>Creando una nueva Pregunta</h1>

<form method="POST" action="{% url 'polls:create_question_post' %}">
  {% csrf_token %}
  <label for="">Here</label>
  <input type="text" name="question_text" id="" placeholder="Titulo de nueva pregunta">
  <input type="submit" value="Enviar">
</form>

polls/templates/general/footer.html
  <footer></footer>
</body>
</html>

polls/templates/general/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{{title}}</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

polls/templates/questions.html
{% include 'general/header.html' with title='Las Preguntas' only %}
{% if questions %}
<ul>
  {% for question in questions %}
  <li><a href="{% url 'polls:single_question' question.id %}">{{question.question_text}}</a></li>
  {% endfor %}
</ul>
{% endif %}
{% include 'general/footer.html' %}

polls/templates/single-question.html
<p>{{question.question_text}}</p>